version: '2'
services:
  web:
    build: .
    volumes:
      - "./:/hotelAPI"
    ports:
     - "3000:3000"
    command: "bin/rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - database_hotel
    links:
      - database_hotel:database_hotel
    stdin_open: true
  database_hotel:
    image: postgres:9.4
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
